server:
  address: 0.0.0.0
  port: 8081

spring:
  profiles:
    active: local
  datasource:
    url:
    username:
    password:
  jpa:
    hibernate:
      ddl-auto:
    properties:
      hibernate:
        dialect:

grpc:
  server:
    port: 6565

management:
  endpoints:
    web:
      exposure:
        include: prometheus
  endpoint:
    prometheus:
      enabled: true

sandbox:
  property: "Hola Mundo!"
