server:
  port: 8081

spring:
  profiles:
    active: local
  datasource:
    url:
    username:
    password:
  jpa:
    hibernate:
      ddl-auto:
    properties:
      hibernate:
        dialect:

grpc:
  server:
    port: 6565

sandbox:
  property: "Hola Mundo!"
